# preload = /home/Piako/Pictures/background/6288242E89BC369B25B911178C015F34.jpg
# wallpaper = ,/home/Piako/Pictures/background/6288242E89BC369B25B911178C015F34.jpg


preload = /home/Piako/Pictures/background/night2.png
wallpaper = ,/home/Piako/Pictures/background/night2.png