# 启动 wayland 桌面前设置一些环境变量
 function set_wayland_env
 {
  # Nvidia配置
  env = LIBVA_DRIVER_NAME,nvidia
  env = XDG_SESSION_TYPE,wayland
  env = GBM_BACKEND,nvidia-drm
  env = __GLX_VENDOR_LIBRARY_NAME,nvidia
  env = WLR_NO_HARDWARE_CURSORS,1


}


set_wayland_env
